# Generated by Django 5.2.11 on 2026-04-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertrule',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='behavior',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='cow_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trackingdata',
            name='timestamp',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='trackingdata',
            index=models.Index(fields=['timestamp', 'behavior'], name='idx_ts_behavior'),
        ),
        migrations.AddIndex(
            model_name='trackingdata',
            index=models.Index(fields=['timestamp', 'cow_id'], name='idx_ts_cowid'),
        ),
    ]
